file=open('output.txt','a')
print("enter text to write to the file:")
text1=input()
file.write(text1)
print("Data succesfully written to output.txt.\n")
print("enter additional text to append :")
text2=input()
file.write(text2)
print("final content of output.txt:\n")
file = open("output.txt", "r")
content = file.read()
print("\n",content)
file.close()
